

import { FriendshipStatus, type User, type Post, type Message, type Comment, ChatTheme, AdminUser } from './types';

export const IMAGE_GENERATION_COST = 60;
export const SPONSOR_CPM_BDT = 300; // Cost Per 1000 Impressions in BDT

export const MOCK_ADMINS: AdminUser[] = [
    { id: 'admin_1', email: 'admin@voicebook.com' }
];

export const CHAT_THEMES: Record<ChatTheme, { name: string, bgGradient: string; myBubble: string; theirBubble: string; text: string; headerText: string; }> = {
    default: {
        name: 'Default',
        bgGradient: 'from-slate-900 to-slate-800',
        myBubble: 'bg-rose-600',
        theirBubble: 'bg-slate-700',
        text: 'text-white',
        headerText: 'text-slate-100',
    },
    sunset: {
        name: 'Sunset',
        bgGradient: 'from-orange-800 via-rose-800 to-indigo-900',
        myBubble: 'bg-indigo-500',
        theirBubble: 'bg-rose-500/80',
        text: 'text-white',
        headerText: 'text-white',
    },
    ocean: {
        name: 'Ocean',
        bgGradient: 'from-cyan-900 to-blue-900',
        myBubble: 'bg-teal-500',
        theirBubble: 'bg-sky-800/80',
        text: 'text-white',
        headerText: 'text-cyan-100',
    },
    forest: {
        name: 'Forest',
        bgGradient: 'from-emerald-900 to-green-900',
        myBubble: 'bg-lime-600',
        theirBubble: 'bg-emerald-700/80',
        text: 'text-white',
        headerText: 'text-green-100',
    },
    classic: {
        name: 'Classic',
        bgGradient: 'from-slate-200 to-gray-200',
        myBubble: 'bg-blue-500',
        theirBubble: 'bg-gray-300',
        text: 'text-black',
        headerText: 'text-gray-800',
    }
};

export const DEFAULT_USER: User = {
    id: 'u_001',
    name: 'Default User',
    avatarUrl: 'https://picsum.photos/seed/default/100/100',
    bio: 'Exploring the world through sound.',
    coverPhotoUrl: 'https://picsum.photos/seed/default_cover/800/300',
    work: 'UX Designer at SoundWave',
    education: 'Studied HCI at University of Washington',
    hometown: 'Seattle, WA',
    currentCity: 'Seattle, WA',
    relationshipStatus: 'Single',
    privacySettings: {
        postVisibility: 'public',
        friendRequestPrivacy: 'everyone',
    },
    blockedUserIds: [],
    voiceCoins: 10,
    role: 'user',
};

export const MOCK_USERS: User[] = [
    { 
        id: 'u_1', 
        name: 'Sumi Ahmed', 
        avatarUrl: 'https://picsum.photos/seed/sumi/100/100', 
        bio: "Designer and dreamer.", 
        friendshipStatus: FriendshipStatus.FRIENDS, // Friend with Shojib
        coverPhotoUrl: 'https://picsum.photos/seed/sumi_cover/800/300',
        work: 'Graphic Designer at Creative Studio',
        education: 'Studied Fine Arts at University of Dhaka',
        hometown: 'Chittagong, Bangladesh',
        currentCity: 'Dhaka, Bangladesh',
        relationshipStatus: 'Single',
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 25,
        role: 'user',
    },
    { 
        id: 'u_2', 
        name: 'Shojib Khan', 
        avatarUrl: 'https://picsum.photos/seed/shojib/100/100', 
        bio: "Engineer building the future.", 
        friendshipStatus: FriendshipStatus.FRIENDS, // This is the logged in user usually
        coverPhotoUrl: 'https://picsum.photos/seed/shojib_cover/800/300',
        work: 'Lead Engineer at VoiceBook',
        education: 'Studied CSE at BUET',
        hometown: 'Dhaka, Bangladesh',
        currentCity: 'San Francisco, CA',
        relationshipStatus: 'In a relationship',
        privacySettings: { postVisibility: 'friends', friendRequestPrivacy: 'friends_of_friends' },
        chatSettings: {
            'u_1': { theme: 'sunset' }
        },
        blockedUserIds: [],
        voiceCoins: 150,
        role: 'user', // No longer an admin by default
    },
    { 
        id: 'u_3', 
        name: 'Sharmin Chowdhury', 
        avatarUrl: 'https://picsum.photos/seed/sharmin/100/100', 
        bio: "Musician and artist.", 
        friendshipStatus: FriendshipStatus.REQUEST_SENT,
        coverPhotoUrl: 'https://picsum.photos/seed/sharmin_cover/800/300',
        education: 'Berklee College of Music',
        currentCity: 'Boston, MA',
        relationshipStatus: 'Single',
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 100,
        role: 'user',
    },
    { 
        id: 'u_4', 
        name: 'Rohan Mahmud', 
        avatarUrl: 'https://picsum.photos/seed/rohan/100/100', 
        bio: "Adventurer and storyteller.", 
        friendshipStatus: FriendshipStatus.PENDING_APPROVAL,
        coverPhotoUrl: 'https://picsum.photos/seed/rohan_cover/800/300',
        work: 'Travel Blogger',
        hometown: 'Sylhet, Bangladesh',
        currentCity: 'On the road',
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 0,
        role: 'user',
    },
    { 
        id: 'u_5', 
        name: 'Nadia Islam', 
        avatarUrl: 'https://picsum.photos/seed/nadia/100/100', 
        bio: "AI researcher and coffee enthusiast.", 
        friendshipStatus: FriendshipStatus.NOT_FRIENDS, // Not friends with Shojib, but friends with Sumi
        coverPhotoUrl: 'https://picsum.photos/seed/nadia_cover/800/300',
        work: 'AI Researcher',
        education: 'MIT',
        currentCity: 'Cambridge, MA',
        relationshipStatus: 'Single',
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 50,
        role: 'user',
    },
    { 
        id: 'u_6', 
        name: 'Anika Tabassum', 
        avatarUrl: 'https://picsum.photos/seed/anika/100/100', 
        bio: "Loves to travel and code.", 
        friendshipStatus: FriendshipStatus.FRIENDS,
        coverPhotoUrl: 'https://picsum.photos/seed/anika_cover/800/300',
        work: 'Remote Developer',
        education: 'Studied at Khulna University',
        hometown: 'Khulna, Bangladesh',
        currentCity: 'Dhaka, Bangladesh',
        relationshipStatus: 'In a relationship',
        privacySettings: { postVisibility: 'friends', friendRequestPrivacy: 'friends_of_friends' },
        blockedUserIds: [],
        voiceCoins: 75,
        role: 'user',
    },
    { 
        id: 'u_7', 
        name: 'Rifat Ahmed', 
        avatarUrl: 'https://picsum.photos/seed/rifat/100/100', 
        bio: "Dhaka's #1 food blogger!", 
        friendshipStatus: FriendshipStatus.NOT_FRIENDS,
        coverPhotoUrl: 'https://picsum.photos/seed/rifat_cover/800/300',
        work: 'Food Blogger',
        education: 'East West University',
        hometown: 'Comilla, Bangladesh',
        currentCity: 'Dhaka, Bangladesh',
        relationshipStatus: 'Single',
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 15,
        role: 'user',
    },
    { 
        id: 'u_8', 
        name: 'Farhana Yasmin', 
        avatarUrl: 'https://picsum.photos/seed/farhana/100/100', 
        bio: "Capturing moments, one click at a time.", 
        friendshipStatus: FriendshipStatus.REQUEST_SENT,
        coverPhotoUrl: 'https://picsum.photos/seed/farhana_cover/800/300',
        work: 'Photographer',
        hometown: 'Chittagong, Bangladesh',
        currentCity: 'Chittagong, Bangladesh',
        relationshipStatus: "It's complicated",
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 5,
        role: 'user',
    },
    { 
        id: 'u_9', 
        name: 'Imran Hasan', 
        avatarUrl: 'https://picsum.photos/seed/imran/100/100', 
        bio: "Founder @ Stealth Startup. Building the next big thing.", 
        friendshipStatus: FriendshipStatus.PENDING_APPROVAL,
        coverPhotoUrl: 'https://picsum.photos/seed/imran_cover/800/300',
        work: 'Startup Founder',
        education: 'IBA, University of Dhaka',
        hometown: 'Dhaka, Bangladesh',
        currentCity: 'Dhaka, Bangladesh',
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'friends_of_friends' },
        blockedUserIds: [],
        voiceCoins: 200,
        role: 'user',
    },
    { 
        id: 'u_10', 
        name: 'John Smith', 
        avatarUrl: 'https://picsum.photos/seed/john/100/100', 
        bio: "Expat living in Dhaka. Exploring Bangladesh!", 
        friendshipStatus: FriendshipStatus.NOT_FRIENDS,
        coverPhotoUrl: 'https://picsum.photos/seed/john_cover/800/300',
        work: 'Diplomat',
        hometown: 'Washington D.C., USA',
        currentCity: 'Dhaka, Bangladesh',
        relationshipStatus: 'Married',
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 10,
        role: 'user',
    },
    { 
        id: 'u_11', 
        name: 'Maria Gomes', 
        avatarUrl: 'https://picsum.photos/seed/maria/100/100', 
        bio: "Artist and painter. My canvas is my world.", 
        friendshipStatus: FriendshipStatus.FRIENDS,
        coverPhotoUrl: 'https://picsum.photos/seed/maria_cover/800/300',
        work: 'Freelance Artist',
        education: 'Faculty of Fine Arts, University of Dhaka',
        hometown: 'Barisal, Bangladesh',
        currentCity: 'Dhaka, Bangladesh',
        privacySettings: { postVisibility: 'friends', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 40,
        role: 'user',
    },
    { 
        id: 'u_12', 
        name: 'Tanvir Rahman', 
        avatarUrl: 'https://picsum.photos/seed/tanvir/100/100', 
        bio: "Fitness enthusiast. #GymLife", 
        friendshipStatus: FriendshipStatus.NOT_FRIENDS,
        coverPhotoUrl: 'https://picsum.photos/seed/tanvir_cover/800/300',
        work: 'Personal Trainer',
        currentCity: 'Dhaka, Bangladesh',
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 8,
        role: 'user',
    },
    { 
        id: 'u_13', 
        name: 'Dr. Sadia Afrin', 
        avatarUrl: 'https://picsum.photos/seed/sadia/100/100', 
        bio: "Saving lives and drinking coffee.", 
        friendshipStatus: FriendshipStatus.FRIENDS,
        coverPhotoUrl: 'https://picsum.photos/seed/sadia_cover/800/300',
        work: 'Doctor at Square Hospital',
        education: 'Dhaka Medical College',
        hometown: 'Mymensingh, Bangladesh',
        currentCity: 'Dhaka, Bangladesh',
        relationshipStatus: 'Engaged',
        privacySettings: { postVisibility: 'friends', friendRequestPrivacy: 'friends_of_friends' },
        blockedUserIds: [],
        voiceCoins: 110,
        role: 'user',
    },
    { 
        id: 'u_14', 
        name: 'David Chen', 
        avatarUrl: 'https://picsum.photos/seed/david/100/100', 
        bio: "Exchange student learning about Bengali culture.", 
        friendshipStatus: FriendshipStatus.NOT_FRIENDS,
        coverPhotoUrl: 'https://picsum.photos/seed/david_cover/800/300',
        education: 'University of Dhaka',
        hometown: 'Beijing, China',
        currentCity: 'Dhaka, Bangladesh',
        relationshipStatus: 'Single',
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 20,
        role: 'user',
    },
    { 
        id: 'u_15', 
        name: 'Fatima Begum', 
        avatarUrl: 'https://picsum.photos/seed/fatima/100/100', 
        bio: "Homemaker and vlogger. Sharing my favorite recipes!", 
        friendshipStatus: FriendshipStatus.NOT_FRIENDS,
        coverPhotoUrl: 'https://picsum.photos/seed/fatima_cover/800/300',
        work: 'Content Creator',
        hometown: 'Rajshahi, Bangladesh',
        currentCity: 'Rajshahi, Bangladesh',
        relationshipStatus: 'Married',
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 55,
        role: 'user',
    },
    { 
        id: 'u_16', 
        name: 'Kabir Hossain', 
        avatarUrl: 'https://picsum.photos/seed/kabir/100/100', 
        bio: "Music is life. Guitarist for the band 'Otopor'.", 
        friendshipStatus: FriendshipStatus.FRIENDS,
        coverPhotoUrl: 'https://picsum.photos/seed/kabir_cover/800/300',
        work: 'Musician',
        hometown: 'Dhaka, Bangladesh',
        currentCity: 'Dhaka, Bangladesh',
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 90,
        role: 'user',
    },
    { 
        id: 'u_17', 
        name: 'Laura Petrova', 
        avatarUrl: 'https://picsum.photos/seed/laura/100/100', 
        bio: "Researcher obsessed with Bengali literature.", 
        friendshipStatus: FriendshipStatus.NOT_FRIENDS,
        coverPhotoUrl: 'https://picsum.photos/seed/laura_cover/800/300',
        work: 'Researcher',
        education: 'SOAS University of London',
        hometown: 'Sofia, Bulgaria',
        currentCity: 'Dhaka, Bangladesh',
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 33,
        role: 'user',
    },
    { 
        id: 'u_18', 
        name: 'Mehedi Hasan', 
        avatarUrl: 'https://picsum.photos/seed/mehedi/100/100', 
        bio: "Pro gamer and streamer. Catch me live!", 
        friendshipStatus: FriendshipStatus.PENDING_APPROVAL,
        coverPhotoUrl: 'https://picsum.photos/seed/mehedi_cover/800/300',
        work: 'Streamer',
        currentCity: 'Dhaka, Bangladesh',
        relationshipStatus: 'Single',
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 42,
        role: 'user',
    },
    { 
        id: 'u_19', 
        name: 'Tasnim Akter', 
        avatarUrl: 'https://picsum.photos/seed/tasnim/100/100', 
        bio: "Architect. Designing beautiful & sustainable spaces.", 
        friendshipStatus: FriendshipStatus.FRIENDS,
        coverPhotoUrl: 'https://picsum.photos/seed/tasnim_cover/800/300',
        work: 'Architect',
        education: 'BUET',
        currentCity: 'Dhaka, Bangladesh',
        privacySettings: { postVisibility: 'friends', friendRequestPrivacy: 'friends_of_friends' },
        blockedUserIds: [],
        voiceCoins: 68,
        role: 'user',
    },
    { 
        id: 'u_20', 
        name: 'Omar Faruq', 
        avatarUrl: 'https://picsum.photos/seed/omar/100/100', 
        bio: "New to VoiceBook. Let's connect!", 
        friendshipStatus: FriendshipStatus.NOT_FRIENDS,
        coverPhotoUrl: 'https://picsum.photos/seed/omar_cover/800/300',
        privacySettings: { postVisibility: 'public', friendRequestPrivacy: 'everyone' },
        blockedUserIds: [],
        voiceCoins: 10,
        role: 'user',
    },
];

const MOCK_COMMENTS_P1: Comment[] = [
    { id: 'c_1', postId: 'p_1', author: MOCK_USERS[1], audioUrl: '#', duration: 5, createdAt: '2024-05-21T08:05:00Z' },
    { id: 'c_2', postId: 'p_1', author: MOCK_USERS[2], audioUrl: '#', duration: 7, createdAt: '2024-05-21T08:10:00Z' },
];

export const MOCK_POSTS: Post[] = [
    {
        id: 'p_1',
        author: MOCK_USERS[0],
        audioUrl: '#',
        caption: 'Just had some amazing coffee this morning. Feeling energized! ☕️',
        duration: 12,
        createdAt: '2024-05-21T08:00:00Z',
        likeCount: 42,
        commentCount: 2,
        comments: MOCK_COMMENTS_P1,
        likedBy: [MOCK_USERS[1], MOCK_USERS[2]],
    },
    {
        id: 'p_2',
        author: MOCK_USERS[1],
        audioUrl: '#',
        caption: 'Working on a new feature for VoiceBook. I think you are all going to love it.',
        duration: 25,
        createdAt: '2024-05-21T07:30:00Z',
        likeCount: 128,
        commentCount: 0,
        comments: [],
        likedBy: [MOCK_USERS[0]],
    },
    {
        id: 'p_3',
        author: MOCK_USERS[2],
        audioUrl: '#',
        caption: 'A short melody I came with today. Let me know what you think!',
        duration: 35,
        createdAt: '2024-05-20T18:45:00Z',
        likeCount: 256,
        commentCount: 0,
        comments: [],
        likedBy: [],
    },
    {
        id: 'p_4',
        author: MOCK_USERS[1],
        audioUrl: '#',
        caption: 'My weekend project: building a mechanical keyboard. The sound is so satisfying.',
        duration: 18,
        createdAt: '2024-05-19T10:00:00Z',
        likeCount: 98,
        commentCount: 0,
        comments: [],
        likedBy: [],
        imageUrl: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=2070&auto=format&fit=crop',
        imagePrompt: 'A custom mechanical keyboard with RGB lighting on a desk.',
    },
];

export let MOCK_MESSAGES: Message[] = [
    { id: 'm1', senderId: 'u_1', recipientId: 'u_2', audioUrl: '#', duration: 8, createdAt: '2024-05-22T10:00:00Z', read: true },
    { id: 'm2', senderId: 'u_2', recipientId: 'u_1', audioUrl: '#', duration: 15, createdAt: '2024-05-22T10:01:00Z', read: true },
    { id: 'm3', senderId: 'u_1', recipientId: 'u_2', audioUrl: '#', duration: 5, createdAt: '2024-05-22T10:02:00Z', read: false }, // Shojib (u_2) has not read this from Sumi (u_1)
    { id: 'm4', senderId: 'u_3', recipientId: 'u_2', audioUrl: '#', duration: 10, createdAt: '2024-05-23T11:00:00Z', read: true },
    { id: 'm5', senderId: 'u_2', recipientId: 'u_3', audioUrl: '#', duration: 12, createdAt: '2024-05-23T11:01:00Z', read: false }, // Sharmin (u_3) has not read this from Shojib (u_2)
];


export const TTS_PROMPTS = {
    welcome: "Welcome to VoiceBook. Say 'log in' or 'sign up', or use the mic.",
    signup_name: "Please say your name.",
    signup_password: "Now say a secure password. I will not display it.",
    signup_confirm_password: "Repeat the password to confirm.",
    signup_password_mismatch: "Passwords do not match. Say the password again.",
    signup_success: "Account created. Loading your feed.",
    login_name: "Say your name. Try 'Shojib Khan'.",
    login_password: "Say your password.",
    login_fail: "Sorry, I couldn't log you in. Please check your details and try again.",
    login_banned: "This account has been banned.",
    login_success: (name: string) => `Welcome back, ${name}. Loading your feed.`,
    feed_loaded: "Playing feed. Say 'play', 'pause', 'next', 'previous', or 'view comments'.",
    record_start: "Recording will start after the beep. Say 'stop' to finish.",
    record_stopped: (duration: number) => `You recorded ${duration} seconds. Say 'post' to publish or 're-record' to redo.`,
    post_success: "Posted. Your voice is live.",
    create_post_prompt: (cost: number) => `Compose your post. You can record audio, generate an image for ${cost} coins, or both.`,
    comment_record_start: "Record your comment after the beep. Say 'stop' to finish.",
    comment_stopped: (duration: number) => `Comment recorded for ${duration} seconds. Say 'post comment' to publish or 're-record' to redo.`,
    comment_post_success: "Your comment has been posted.",
    comment_suspended: "Your commenting privileges have been temporarily suspended.",
    like_success: (author: string) => `You liked ${author}'s post.`,
    error_generic: "Sorry, I didn't catch that. Could you say it again, please?",
    help: "You can say commands like 'next post', 'record a new voice', or 'search for a friend'.",
    profile_loaded: (name: string, isCurrentUser: boolean) => isCurrentUser 
        ? `Viewing your profile. Say 'edit profile' or scroll through your posts.` 
        : `Viewing ${name}'s profile. Say 'add friend', 'send message', or 'go back'.`,
    friend_request_sent: (name: string) => `Friend request sent to ${name}.`,
    friend_request_privacy_block: (name: string) => `Sorry, ${name} is not accepting friend requests right now.`,
    friend_requests_loaded: "Viewing friend requests. Say 'accept' or 'decline' followed by the name.",
    friend_request_accepted: (name: string) => `You are now friends with ${name}.`,
    friend_request_declined: (name: string) => `Friend request from ${name} declined.`,
    no_friend_requests: "You have no new friend requests.",
    friends_loaded: "Viewing your friends. You can view requests, suggestions, or all friends.",
    post_details_loaded: "Showing post details. You can listen to comments or record your own.",
    conversations_loaded: "Here are your conversations. Say the name of the person you want to chat with.",
    message_screen_loaded: (name: string) => `Chatting with ${name}. Say 'record message' to start.`,
    message_record_start: "Recording message. Say 'stop' when you are done.",
    message_record_stopped: (duration: number) => `Recorded for ${duration} seconds. Say 'send message' or 're-record'.`,
    message_sent: "Message sent.",
    chat_deleted: "Chat deleted.",
    chat_theme_changed: (themeName: string) => `Theme changed to ${themeName}.`,
    back_to_feed: "Returning to your feed.",
    settings_opened: "Opening settings. You can say 'change work to...', 'set post visibility to friends', or 'save settings'.",
    settings_saved: "Your settings have been saved.",
    privacy_setting_updated: (setting: string, value: string) => `${setting} has been set to ${value}. Say 'save settings' to confirm.`,
    user_blocked: (name: string) => `You have blocked ${name}. They will not be able to see your posts or interact with you.`,
    user_unblocked: (name: string) => `${name} has unblocked.`,
    search_results_loaded: (count: number) => `Found ${count} results. Say 'select' and a number to view a profile.`,
    search_no_results: (query: string) => `No results found for "${query}".`,
    reward_claim_success: (coins: number) => `Success! ${coins} Voice Coins have been added to your wallet.`,
    transaction_failed: "Transaction failed. Please try again.",
    image_generation_insufficient_coins: (cost: number, balance: number) => `You need ${cost} Voice Coins to generate an image, but you only have ${balance}. Watch an ad to earn more.`,
    image_generation_success_with_coins: (cost: number) => `Transaction successful! ${cost} Voice Coins deducted. Generating image...`,
};